### ISSUE TITLE
[2019-10-30]  HTML 與 CSS 基礎

### ISSUE THREAD

**Issue by gracekrcx** [healthyspi/weekly-notes#13]
### Selector
兩個連在一起就是必須都符合(同時符合)
1. p.p  `<p class=‘p’>` 
2. span.p   `<span class=’p’>!!!</span>`

```js 
// div .p --> div 底下的 class name p，不管幾層都會有反應 
// X Y (all level all Y)
<div>
 <div class='p'>第一層</div>  
 <span class='p'>第一層</span>  
 <div class='p'>第一層</div>  
 <span>
 <div class='p'>第二層</div> 
</span>
</div>
```

3. X > Y
X 底下的第一層的所有 Y 都會有反應 (just next level all Y)
[link](https://www.w3schools.com/cssref/sel_element_gt.asp)

4. X + Y
(1) 與 X 同層 
(2) 順序在 X 之後的第一個 Y (after X first Y)
[link](https://www.w3schools.com/cssref/sel_element_pluss.asp)
```js
// 與 ul 同層，且只有 ul 後面的第一個 p 會有反應
ul + p {
   color: red;
}
```

5. X ~ Y 
(1) 與 X 同層 
(2) 順序在 X 之後的 Y (after X all Y)
都會有反應
[link](https://www.w3schools.com/cssref/sel_gen_sibling.asp)

```js
// 與 ul 同層，順序在 ul 之後的 p 會有反應
ul ~ p {
   color: red;
}
```
### Transition 漸變動畫
Transitions 讓你可以定義元件在兩個狀態之間切換的轉場效果
1. transition: all 0.3s eas-in

### Transform 對元素做一些改變
transform CSS 屬性可以讓你修改 CSS 可視化格式模型（visual formatting model）的空間維度。使用此屬性，元素可以被平移、旋轉、縮放和傾斜。

1. transform: scale(1.2)
2. transform: translateX(10)
3. transform: rotate(10deg)

### Box Modal 
1. Box Modal 每個東西都是一個盒子（Box）
2. 行內元素不能設定，寬高和上下 margin

### position
1. position : relative 根據原本的參考點做定位
2. position : absolutely 會參考離他最近的 position 不是 static 的點，relative 和 absolutely  都可以，設定成自己的參考點
3. position: sticky (relative and fixed positioning)

![Alt text](https://www.internetingishard.com/html-and-css/advanced-positioning/css-positioning-schemes-790d5b.png)
### attr
```js
<a href="https://www.google.com" data-hello='hello'>google</a>

a::before{
  content: attr(href);
  color:red;
}
a::after{
  content: attr(data-hello);
  color:green;
}
```

參考資源：
[html & css is hard](https://internetingishard.com/html-and-css/)
[Learn to Code HTML & CSS](https://learn.shayhowe.com/html-css/)
[MarkSheet](https://marksheet.io/)
[CSS 偽元素 ( before 與 after )](https://www.oxxostudio.tw/articles/201706/pseudo-element-1.html)
[The 30 CSS Selectors You Must Memorize](https://code.tutsplus.com/tutorials/the-30-css-selectors-you-must-memorize--net-16048)
[html5up](https://html5up.net/)
[CSS Selector Reference](https://www.w3schools.com/cssref/css_selectors.asp)

**Comment by gracekrcx** [comment]
[Creating parallax scrolling animations like the Apple iPhone XS page in Webflow - Tutorial](https://www.youtube.com/watch?v=Evo1lgy-ZRg)

**Comment by gracekrcx** [comment]
CSS 預處理器 (preprocessor)
用程式化的方法寫 css 然後在 complie 成真的 css

- Scss/ Sass
- Less
- Stylus

**Comment by gracekrcx** [comment]
###  transition 分開設定時間
background-color, width, height, rotate 各自設定

```css
.box {
  border-style: solid;
  border-width: 1px;
  display: block;
  width: 100px;
  height: 100px;
  background-color: #0000ff;
  transition: width 2s, height 2s, background-color 2s, transform 2s;
}

.box:hover {
  background-color: #ffcccc;
  width: 200px;
  height: 200px;
  rotate: 180deg;
}
```
