### ISSUE TITLE
[2019-12-16] CSS preprocessor

### ISSUE THREAD

**Issue by gracekrcx** [healthyspi/weekly-notes#44]
### CSS preprocessor 是什麼？
1. 用程式化的方法寫 CSS，最後 compile 成真的 CSS
2. 著重在用『程式』的方法寫 css

### 輸出方式
```js
scss index.sass index.css
```
index.sass 編譯成 index.css

### Scss/Sass
Scss：有分號有大括號
![img](https://bit.ly/2zGs4ED)
Sass：沒有分號，沒有大括號
![img](https://bit.ly/2YamJyQ)

### Nesting(夠直覺)
```css
.box {
 display : none;
 .btn {
  width : 100px;
  .text {
   color : green;
  }
  .label {
   font-size : 20px;
  }
 }
}
```

### Parent
```css
.card {
  width: 100px;
  &__box {
    width: 30px;
    &--disabled {
     display: none;
    }
  }
}

// compile to
.card { 
  width: 100px; 
}
.card__box {
  width: 30px;
}
.card__box--disabled {
  display: none;
}

```
### Mixin（function）
```css
@mixin transform($property) {
 -webkit-transform: $property*2;
 -ms-transform: $property;
 transform: $property;
}

.box {
 @include transform(rotate(30deg));
}
```

### import 
就可以想成是『複製』『貼上』到檔案裡，跟 php 和 js 是一樣的

### PostCSS
1. css 檔案，經過 PostCSS，轉成別的東西（把現有的 css 轉換成別的形式）
2. 著重在 css 跨 browser 的部分
2. postcss/autoprefixer
